### ISSUE TITLE
Crash on testing requirements

### ISSUE THREAD

**Issue by mcapraro** [gever/bwx-adventure#24]
there is a bug in the latest version when requirements are tested. in bwx-game.py, when you try and go into the elevator, which requires the pebble and the key, there is a crash:

```

        --=( You are in the Intersection )=--        

A boring intersection. There is a passageway to the
north that leads to the shop. To the east is the elevator
landing, to the west is the guest lounge, and to the
south is the reception desk. There is nothing to do here.

> go east
Traceback (most recent call last):
  File "bwx-game.py", line 310, in <module>
    my_game.run(update)
  File "/home/ubuntu/workspace/advent.py", line 417, in run
    if f( actor, noun, words ):
  File "/home/ubuntu/workspace/advent.py", line 658, in act_go1
    if loc == None:
  File "/home/ubuntu/workspace/advent.py", line 511, in go
    if set(c.point_b.requirements).issubset(set(self.hero.inventory)):
AttributeError: 'Location' object has no attribute 'hero'
```

it seems with the refactoring, we lost a reference to hero in location. should Location have a reference to the Game object? then it would be able to find hero through self.game. hero, or is there a better way to get the hero from the Location instance?

**Comment by mcapraro** [comment]
oops, spoke too soon. we do have a reference to game in Location, just had to tweak the code. nevermind, fixed :)
